// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sparseLU
Rcpp::List sparseLU(const std::vector<int>& Ap, const std::vector<int>& Ai, const std::vector<double>& Ax);
RcppExport SEXP _sparselu_sparseLU(SEXP ApSEXP, SEXP AiSEXP, SEXP AxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type Ap(ApSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type Ai(AiSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type Ax(AxSEXP);
    rcpp_result_gen = Rcpp::wrap(sparseLU(Ap, Ai, Ax));
    return rcpp_result_gen;
END_RCPP
}
// sparseLU_solve
Rcpp::NumericVector sparseLU_solve(const std::vector<int>& Ap, const std::vector<int>& Ai, const std::vector<double>& Ax, const std::vector<double>& b);
RcppExport SEXP _sparselu_sparseLU_solve(SEXP ApSEXP, SEXP AiSEXP, SEXP AxSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type Ap(ApSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type Ai(AiSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type Ax(AxSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(sparseLU_solve(Ap, Ai, Ax, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sparselu_sparseLU", (DL_FUNC) &_sparselu_sparseLU, 3},
    {"_sparselu_sparseLU_solve", (DL_FUNC) &_sparselu_sparseLU_solve, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_sparselu(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
