# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparseLU <- function(Ap, Ai, Ax) {
    .Call(`_sparselu_sparseLU`, Ap, Ai, Ax)
}

sparseLU_solve <- function(Ap, Ai, Ax, b) {
    .Call(`_sparselu_sparseLU_solve`, Ap, Ai, Ax, b)
}

